### ISSUE TITLE
Unable to use enum with aliases

### ISSUE THREAD

**Issue by reubeno** [reubeno/NClap#36]
Saw the exception below thrown when trying to parse an enum like this:

```
enum Foo
{
    SomeValue,
    AliasForSomeValue = SomeValue,

    OtherValue,
    AliasForOtherValue = OtherValue
}
```

Exception details:
```
Unhandled Exception: System.ArgumentException: An item with the same key has already been added.    at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NClap.Types.EnumArgumentType..ctor(Type type)
   at NClap.Types.EnumArgumentType.Create(Type type)
   at NClap.Types.ArgumentType.TryGetType(Type type, IArgumentType& argType)
   at NClap.Types.ArgumentType.GetType(Type type)
   at NClap.Metadata.ArgumentBaseAttribute.GetArgumentType(Type type)
   at NClap.Parser.ArgumentDefinition..ctor(IMutableMemberInfo member, ArgumentBaseAttribute attribute, ArgumentSetAttribute setAttribute, CommandLineParserOptions options, Object defaultFieldValue, IMutableMemberInfo parentMember, Object fixedDestination)
   at NClap.Parser.ArgumentSetDefinition.CreateArgumentDescriptor(IMutableMemberInfo member, ArgumentBaseAttribute attribute, Object defaultValues, ArgumentSetAttribute setAttribute, CommandLineParserOptions options, Object fixedDestination)
   at NClap.Parser.ArgumentSetDefinition.CreateArgumentDescriptorsIfApplicable(IMutableMemberInfo member, Object defaultValues, ArgumentSetAttribute setAttribute, CommandLineParserOptions options, Object fixedDestination)
   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NClap.Parser.ArgumentSetDefinition.AddArgumentsFromTypeWithAttributes(Type defininingType, Object defaultValues, Object fixedDestination)
   at NClap.Parser.CommandLineParserEngine..ctor(Type type, Object defaultValues, CommandLineParserOptions options)
   at NClap.CommandLineParser.ParseWithUsage[T](IEnumerable`1 arguments, T destination, CommandLineParserOptions options, UsageInfoOptions usageInfoOptions)
```

**Comment by reubeno** [comment]
Fixed.
