### ISSUE TITLE
.net 5.0: No matching command constructor could be found on type

### ISSUE THREAD

**Issue by maxlem** [reubeno/NClap#84]
I have a weird instantiation bug since I ported to .net5. Happens only with the HelpCommand<> class

```
public enum ApiCommands
{
  [HelpCommand(ShortName = "h", LongName = "help", Description = "Help")]
  Help,
}

```

an exception is raised at CommandGroupArgumentType@106
```
            try
            {
                return commandGroupConstructor.Invoke(new[] { groupOptions, selection, context.ContainingObject });
            }
            catch (TargetInvocationException ex)
            {
                throw ex.InnerException;
            }
```
StackTrace
```
   at NClap.Parser.CommandDefinition.Instantiate(ServiceConfigurer serviceConfigurer) in /.../NClap/src/NClap/Parser/CommandDefinition.cs:line 61
   at NClap.Metadata.CommandGroup`1.InstantiateCommand(IEnumArgumentType commandTypeType, Object selection) in /.../NClap/src/NClap/Metadata/CommandGroup`1.cs:line 189
   at NClap.Metadata.CommandGroup`1.InstantiateCommand(Object selection) in /.../NClap/src/NClap/Metadata/CommandGroup`1.cs:line 162
   at NClap.Metadata.CommandGroup`1.set_SelectedCommand(Object value) in /.../NClap/src/NClap/Metadata/CommandGroup`1.cs:line 154
   at NClap.Metadata.CommandGroup`1..ctor(CommandGroupOptions options, Object selection, Object parentObject) in /.../NClap/src/NClap/Metadata/CommandGroup`1.cs:line 74
```

**Comment by maxlem** [comment]
turns out I was not using .net5 reflection package. There was also a parsing error in my ApiCommands actual implementation.
